name: harian
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.0
  d_session: ^0.0.3
  fd_log: ^0.0.7
  http: ^1.2.2
  intl: ^0.19.0
  get: ^4.6.6
  gap: ^3.0.1
  google_fonts: ^6.2.1
  d_info: ^0.2.0
  d_chart: ^2.0.0
  calendar_view: ^1.2.0
  google_generative_ai: ^0.4.5
  flutter_markdown: ^0.7.3+1
  image_picker: ^1.1.2
  circle_nav_bar: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"
  min_sdk_android: 21 
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#ffffff"
    theme_color: "#7733de"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/images/icon.png"
